# Generated by Django 3.2.7 on 2021-09-10 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='profiles')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('color', models.IntegerField(choices=[(1, 'Blue'), (2, 'Yellow'), (3, 'Red'), (4, 'Green'), (5, 'Black')])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.PositiveIntegerField()),
                ('is_public', models.BooleanField(default=False)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.notebook')),
            ],
        ),
    ]
