# Generated by Django 3.2.7 on 2021-09-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notebook_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
