# Generated by Django 3.2.7 on 2021-09-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_note_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('blue', 'blue'), ('red', 'red'), ('green', 'green'), ('yellow', 'yellow')], default='yellow', max_length=6),
        ),
    ]
