# Generated by Django 3.2.7 on 2021-09-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_notebook_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='color',
            field=models.CharField(choices=[('blue', 'blue'), ('red', 'red'), ('green', 'DarkOliveGreen'), ('yellow', 'Gold'), ('CadetBlue', 'CadetBlue'), ('Lavender', 'Lavender'), ('LightBlue', 'LightBlue')], default='Lavender', max_length=30),
        ),
    ]
