# Generated by Django 3.2.7 on 2021-09-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_auto_20210913_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(choices=[('#ccf', 'Blue'), ('red', 'DarkRed'), ('#cfc', 'Green'), ('#ffc', 'Yellow'), ('CadetBlue', 'CadetBlue'), ('Lavender', 'Lavender'), ('#ffcce5', 'Pink'), ('BurlyWood', 'BurlyWood'), ('#f9f9f9', 'Silver'), ('Cornsilk', 'Cornsilk'), ('IndianRed ', 'IndianRed '), ('LightGreen', 'LightGreen'), ('LightSlateGray', 'LightSlateGray'), ('PaleGoldenRod', 'PaleGoldenRod')], default='yellow', max_length=30),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='color',
            field=models.CharField(choices=[('#ccf', 'Blue'), ('red', 'DarkRed'), ('#cfc', 'Green'), ('#ffc', 'Yellow'), ('CadetBlue', 'CadetBlue'), ('Lavender', 'Lavender'), ('#ffcce5', 'Pink'), ('BurlyWood', 'BurlyWood'), ('#f9f9f9', 'Silver'), ('Cornsilk', 'Cornsilk'), ('IndianRed ', 'IndianRed '), ('LightGreen', 'LightGreen'), ('LightSlateGray', 'LightSlateGray'), ('PaleGoldenRod', 'PaleGoldenRod')], default='Lavender', max_length=30),
        ),
    ]
